// Copyright 2021, Shulhan <ms@kilabit.info>. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package trunks

import "fmt"

//
// WebSocketRunHandler define a function type that will be called to run the
// WebSocket target.
//
type WebSocketRunHandler func(rr *RunRequest) (interface{}, error)

//
// WebSocketTarget define the target to test WebSocket service.
//
type WebSocketTarget struct {
	Headers KeyFormInput

	// Params contains additional parameters to be passed when running
	// the WebSocket handler.
	// It could be custom HTTP headers, query parameters, or arguments in
	// the body. Its up to the user on how to use the Params inside the
	// Run handler.
	// This field is optional.
	Params KeyFormInput

	Run WebSocketRunHandler `json:"-"`

	// ID of target, optional.
	// If its empty, it will generated by normalized the value of Name.
	ID string

	Name string // Name of target, required.
	Hint string // Description about what this WebSocket target is doing.
}

func (wst *WebSocketTarget) init() (err error) {
	if len(wst.Name) == 0 {
		return fmt.Errorf("empty WebSocketTarget Name")
	}
	if len(wst.ID) == 0 {
		wst.ID = generateID(wst.Name)
	}
	if wst.Headers == nil {
		wst.Headers = KeyFormInput{}
	}
	if wst.Params == nil {
		wst.Params = KeyFormInput{}
	}
	return nil
}
