= trunks CHANGELOG
Shulhan <ms@kilabit.info>
:toc:
:sectanchors:
:sectlinks:

[#v0_4_0]
== trunks v0.4.0 (2023-05-16)

[#v0_4_0__bug_fixes]
===  Bug fixes

all: fix panic when attacking HTTP due to nil Attack handler::
+
In attack endpoint, check if the Attack is nil before we push the request
to attack queue.

[#v0_4_0__enhancements]
===  Enhancements

_www: replace WebSocket handlers with HTTP endpoints::
+
The Attack and attack Cancel now call the HTTP endpoints.

all: add boolean Kind for FormInput, FormInputKindBoolean::
+
--
The FormInputKindBoolean only used for convertion, for example
ToJsonObject.
In the WUI, it still rendered as string, not as checkbox.

FormInput with this Kind will be converted to true in ToJsonObject if
the Value is either "true", "yes", or "1".
--

all: check and call ConvertParams when running HttpTarget::
+
If the ConvertParams field is set, use it to convert the parameters into
desired type.

[#v0_4_0__chores]
=== Chores

all: move the _doc directory under _www::

all: convert the README from asciidoc to markdown::

all: remove WebSocket server::
+
Using WebSocket for communication in client require additional
setup, especially if its behind proxy.
For example, if we serve the trunks server under domain testing.local
behind proxy, we need to setup route for the WebSocket too.

go.mod: set Go version to 1.19 and update all dependencies::


[#v0_3_0]
== trunks v0.3.0 (2022-08-25)

This release set the minimum Go version to 1.18 and update all modules.

[#v0_3_0_chores]
===  Chores

all: group all documentations under directory _doc::
+
The _doc directory provides an entry point for all documentation.
While at it we reformat the README to use AsciiDoc markup.

example: fix the HTTP POST handler::
+
Remove call to ParseMultipartform since the request type is
x-www-form-urlencoded not multipart/form-data.

all: remove unused field Locker in RunRequest::

all: fix all linter warnings::
+
Some linter, govet, warns about possible copied Mutex on HttpRequest.
To fix this we implement method clone and Stringer on HttpRequest.


[#v0_2_0]
== trunks v0.2.0 (2022-03-13)

Release trunks under GPL 3.0 or later license.

See https://kilabit.info/journal/2022/gpl for more information.


[#v0_1_0]
== trunks v0.1.0 (2022-02-05)

Module trunks is a library and HTTP service that provide web user interface
to test HTTP service, similar to Postman, and for load testing.

For the load testing we use vegeta [1] as the backend.

[1] https://github.com/tsenart/vegeta

// SPDX-FileCopyrightText: 2021 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-or-later
